language: c
dist: bionic
sudo: false

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - pkg-config gfortran netcdf-bin libnetcdf-dev libnetcdff-dev wget libhdf5-dev

env:

before_script:

script:
  - pwd
  - ls /usr/include
  - export FCFLAGS=-I/usr/include
  - autoreconf -i
  - ./configure
  - make -j distcheck
  - ls


