language: c
dist: bionic
sudo: false

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - pkg-config gfortran netcdf-bin libnetcdf-dev libnetcdff-dev wget #libhdf5-dev

env:

before_script:
#  - pushd /usr/lib/x86_64-linux-gnu
#  - sudo ln -s libhdf5_serial.so.100.0.1 libhdf5.so
#  - sudo ln -s libhdf5_serial_hl.so.100.0.0 libhdf5_hl.so
#  - ls -l libhdf5*
#  - popd
  - export MY_DIR=`pwd`/local
  - wget https://github.com/live-clones/hdf5/archive/hdf5-1_10_6.tar.gz
  - tar zxf hdf5-1_10_6.tar.gz
  - ls
  - pushd hdf5-hdf5-1_10_6
  - ./configure --prefix=$MY_DIR
  - make install
  - popd

script:
  - pwd
#  - ls /usr/include
#  - ls /usr/lib/x86_64-linux-gnu
  - export MY_DIR=`pwd`/local 
  - export FCFLAGS=-I/usr/include
  - export CPPFLAGS=-I${MY_DIR}/include
  - export LDFLAGS=-L${MY_DIR}/lib
  - export HDF5_PLUGIN_PATH=`pwd`/hdf5_plugins/BZIP2/src
  - echo $HDF5_PLUGIN_PATH
  - autoreconf -i
  - ./configure
#  - make -j distcheck
  - make
  - cd test_h5
  - make tst_h_bzip2
  - ./tst_h_bzip2
  - ls -l
  - ncdump -s tst_h_bzip2.h5
  - ./tst_h_bzip2


