name: build all

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_all:

    runs-on: ubuntu-latest

    env:
      CPPFLAGS: "-I/home/runner/hdf5/include -I/home/runner/netcdf-c/include -I/home/runner/netcdf-fortran/include"
      LDFLAGS: "-L/home/runner/hdf5/lib -L/home/runner/netcdf-c/lib -L/home/runner/netcdf-fortran/lib"
      HDF5_PLUGIN_PATH: "/home/runner/plugin"
      DEPENDENCIES_CACHE_KEY: "deps-${{ runner.os }}-hdf5-1.14.6-netcdf-4.9.3-fortran-4.5.4-1"

    steps:
    - uses: actions/checkout@v4
    - name: Installs
      run: |
        sudo apt-get install doxygen graphviz liblz4-dev wget
    - name: cache-dependencies
      id: cache-dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/hdf5
          ~/netcdf-c
          ~/netcdf-fortran
          /home/runner/plugin
        key: ${{ env.DEPENDENCIES_CACHE_KEY }}

    - name: build-dependencies
      if: steps.cache-dependencies.outputs.cache-hit != 'true'
      run: |
        set -x
        # Create plugin directory
        mkdir -p /home/runner/plugin
        
        # Build HDF5
        wget https://github.com/HDFGroup/hdf5/archive/refs/tags/hdf5-1.14.6.tar.gz &> /dev/null
        tar -xzf hdf5-1.14.6.tar.gz
        pushd hdf5-hdf5-1.14.6
        ./configure --prefix=/home/runner/hdf5 --disable-tools --disable-fortran --disable-cxx 
        make
        sudo make install
        popd
        
        # Build NetCDF-C
        wget https://github.com/Unidata/netcdf-c/archive/refs/tags/v4.9.3.tar.gz  &> /dev/null
        tar -xzf v4.9.3.tar.gz
        pushd netcdf-c-4.9.3
        ./configure --prefix=/home/runner/netcdf-c --disable-dap --disable-utilities --with-plugin-dir=/home/runner/plugin
        make -j
        sudo make install
        popd
        
        # Build NetCDF-Fortran
        wget https://github.com/Unidata/netcdf-fortran/archive/v4.5.4.tar.gz &> /dev/null
        tar -xzf v4.5.4.tar.gz
        pushd netcdf-fortran-4.5.4
        ./configure --prefix=/home/runner/netcdf-fortran
        make -j
        sudo make install
        popd
        
        # Verify plugin directory
        ls -l /home/runner/plugin || echo "Plugin directory is empty or doesn't exist"
    - name: configure and build
      run: |
        set -x
        autoreconf -i
        export DISTCHECK_CONFIGURE_FLAGS="--with-hdf5-plugin-path=/home/runner/plugin --enable-fortran"
        export HDF5_PLUGIN_PATH=/home/runner/plugin
        ls -l $HDF5_PLUGIN_PATH || echo "Plugin directory is empty or doesn't exist"
        ./configure --with-hdf5-plugin-path=/home/runner/plugin --enable-fortran --disable-bzip2
        make VERBOSE=1 check
        cd test
        ./tst_perf
