name: parallel I/O build netcdf-c-4.8.0-hdf-5.1.10.7

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      CPPFLAGS: "-I/home/runner/hdf5/include -I/home/runner/netcdf-c/include -I/home/runner/netcdf-fortran/include"
      LDFLAGS: "-L/home/runner/hdf5/lib -L/home/runner/netcdf-c/lib -L/home/runner/netcdf-fortran/lib"
      HDF5_PLUGIN_PATH: "/home/runner/plugin"

    steps:
    - uses: actions/checkout@v2
    - name: Installs
      run: |
        sudo apt-get install doxygen graphviz liblz4-dev libzstd-dev
    - name: cache-mpich
      id: cache-mpich
      uses: actions/cache@v2
      with:
        path: ~/mpich
        key: mpich-${{ runner.os }}-3.3.2
    - name: build-mpich
      if: steps.cache-mpich.outputs.cache-hit != 'true'
      run: |
        wget http://www.mpich.org/static/downloads/3.3.2/mpich-3.3.2.tar.gz &> /dev/null
        tar -xzf mpich-3.3.2.tar.gz
        pushd mpich-3.3.2
        ./configure --prefix=/home/runner/mpich
        make
        sudo make install
        popd
    - name: cache-hdf5
      id: cache-hdf5
      uses: actions/cache@v2
      with:
        path: ~/hdf5
        key: hdf5-${{ runner.os }}-1.10.7-mpich-3.3.2

    - name: build-hdf5
      if: steps.cache-hdf5.outputs.cache-hit != 'true'
      run: |
        set -x
        export PATH="/home/runner/mpich/bin:$PATH"
        export CC=/home/runner/mpich/bin/mpicc
        wget https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.10/hdf5-1.10.7/src/hdf5-1.10.7.tar.gz &> /dev/null
        tar -xzf hdf5-1.10.7.tar.gz
        pushd hdf5-1.10.7
        ./configure --prefix=/home/runner/hdf5 --enable-parallel --disable-tools --disable-fortran --disable-cxx --enable-parallel-tests
        make
        sudo make install
        popd
    - name: cache-netcdf-c
      id: cache-netcdf-c
      uses: actions/cache@v2
      with:
        path: ~/netcdf-c
        key: netcdf-c-${{ runner.os }}-4.8.0-mpich-3.3.2

    - name: build-netcdf-c
      if: steps.cache-netcdf-c.outputs.cache-hit != 'true'
      run: |
        set -x
        export PATH="/home/runner/mpich/bin:$PATH"
        export CC=/home/runner/mpich/bin/mpicc
        wget https://github.com/Unidata/netcdf-c/archive/refs/tags/v4.7.4.tar.gz &> /dev/null
        tar -xzf v4.7.4.tar.gz
        pushd netcdf-c-4.8.0
        ./configure --prefix=/home/runner/netcdf-c --disable-dap --disable-utilities
        make -j
        sudo make install
        popd
    - name: cache-netcdf-fortran
      id: cache-netcdf-fortran
      uses: actions/cache@v2
      with:
        path: ~/netcdf-fortran
        key: netcdf-fortran-${{ runner.os }}-4.5.3-mpich-3.3.2-1

    - name: build-netcdf-fortran
      if: steps.cache-netcdf-fortran.outputs.cache-hit != 'true'
      run: |
        set -x
        export PATH="/home/runner/mpich/bin:$PATH"
        export CC=/home/runner/mpich/bin/mpicc
        export FC=/home/runner/mpich/bin/mpifort
        wget https://github.com/Unidata/netcdf-fortran/archive/v4.5.3.tar.gz &> /dev/null
        tar -xzf v4.5.3.tar.gz
        pushd netcdf-fortran-4.5.3
        ./configure --prefix=/home/runner/netcdf-fortran
        make -j
        sudo make install
        popd
    - name: configure and build
      run: |
        set -x
        echo $HDF5_PLUGIN_PATH
        export PATH="/home/runner/mpich/bin:$PATH"
        export CC=/home/runner/mpich/bin/mpicc
        export FC=/home/runner/mpich/bin/mpifort
        autoreconf -i
        ./configure --with-hdf5-plugin-path=/home/runner/plugin --enable-fortran --enable-parallel-tests
        make -j check
        

