name: build versions

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        hdf5: [ 1_10_6 ]
    env:
      CPPFLAGS: "-I/home/runner/hdf5${{ matrix.hdf5 }}/include -I/home/runner/netcdf-c/include -I/home/runner/netcdf-fortran/include"
      LDFLAGS: "-L/home/runner/hdf5${{ matrix.hdf5 }}/lib -L/home/runner/netcdf-c/lib -L/home/runner/netcdf-fortran/lib"
      HDF5_PLUGIN_PATH: "/home/runner/plugin"

    steps:
    - uses: actions/checkout@v2
    - name: Installs
      run: |
        sudo apt-get install doxygen graphviz liblz4-dev libzstd-dev wget
    - name: cache-hdf5
      id: cache-hdf5
      uses: actions/cache@v2
      with:
        path: ~/hdf5-${{ matrix.hdf5 }}
        key: hdf5-${{ runner.os }}-${{ matrix.hdf5 }}

    - name: build-hdf5
      if: steps.cache-hdf5.outputs.cache-hit != 'true'
      run: |
        set -x
        wget https://github.com/HDFGroup/hdf5/archive/refs/tags/hdf5-${{ matrix.hdf5 }}.tar.gz  &> /dev/null
        tar -xzf hdf5-${{ matrix.hdf5 }}.tar.gz
        pushd hdf5-${{ matrix.hdf5 }}
        ./configure --prefix=/home/runner/hdf5 --disable-tools --disable-fortran --disable-cxx 
        make
        sudo make install
        popd
    - name: cache-netcdf-c
      id: cache-netcdf-c
      uses: actions/cache@v2
      with:
        path: ~/netcdf-c
        key: netcdf-c-${{ runner.os }}-4.7.4

    - name: build-netcdf-c
      if: steps.cache-netcdf-c.outputs.cache-hit != 'true'
      run: |
        set -x
        wget https://github.com/Unidata/netcdf-c/archive/refs/tags/v4.7.4.tar.gz  &> /dev/null
        tar -xzf v4.7.4.tar.gz
        ls -l
        pushd netcdf-c-4.7.4
        ./configure --prefix=/home/runner/netcdf-c --disable-dap --disable-utilities
        make -j
        sudo make install
        popd
    - name: cache-netcdf-fortran
      id: cache-netcdf-fortran
      uses: actions/cache@v2
      with:
        path: ~/netcdf-fortran
        key: netcdf-fortran-${{ runner.os }}-4.5.3-mpich-3.3.2

    - name: build-netcdf-fortran
      if: steps.cache-netcdf-fortran.outputs.cache-hit != 'true'
      run: |
        set -x
        wget https://github.com/Unidata/netcdf-fortran/archive/v4.5.3.tar.gz &> /dev/null
        tar -xzf v4.5.3.tar.gz
        pushd netcdf-fortran-4.5.3
        ./configure --prefix=/home/runner/netcdf-fortran
        make -j
        sudo make install
        popd
    - name: configure and build
      run: |
        set -x
        echo $HDF5_PLUGIN_PATH
        autoreconf -i
        export DISTCHECK_CONFIGURE_FLAGS="--with-hdf5-plugin-path=/home/runner/plugin --enable-fortran"
        ./configure --with-hdf5-plugin-path=/home/runner/plugin --enable-fortran
        make -j distcheck
