name: macos build all

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    env:
      CFLAGS: "-Wno-implicit-function-declaration"
      HDF5_PLUGIN_PATH: "/Users/runner/plugin"

    steps:
    - uses: actions/checkout@v2
    - name: Installs
      run: |
        brew install doxygen lz4 zstd
    - name: cache-hdf5
      id: cache-hdf5
      uses: actions/cache@v2
      with:
        path: ~/hdf5
        key: hdf5-${{ runner.os }}-1.10.6

    - name: build-hdf5
      if: steps.cache-hdf5.outputs.cache-hit != 'true'
      run: |
        set -x
        wget https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.10/hdf5-1.10.6/src/hdf5-1.10.6.tar.gz &> /dev/null
        tar -xzf hdf5-1.10.6.tar.gz
        pushd hdf5-1.10.6
        ./configure --prefix=/Users/runner/hdf5 --disable-tools --disable-fortran --disable-cxx --enable-build-mode=clean
        make
        make install
        popd
    - name: configure and build
      run: |
        echo $HDF5_PLUGIN_PATH
        autoreconf -i
        export DISTCHECK_CONFIGURE_FLAGS="--with-hdf5-plugin-path=/Users/runner/plugin --enable-fortran"
        ./configure --with-hdf5-plugin-path=/Users/runner/plugin --enable-fortran
